Audit usages of `TH.mkName`; inform users about potential imports
Audit all usages of `TH.mkName`, and make them more explicit.

Add note to `mkHsName`, which uses `TH.mkName` internally, and inform potential future developers of its pitfall.

Add `lookupTypeName` to `Guasi`, so we can use it, and inform the user about names missing in a splice. This works really well, for example, removing the `LibC` import in our `Test02.hs` leads to an informative compilation error:

```
External types not in scope. Add the following import(s):
    import HsBindgen.Runtime.LibC qualified
```

Ensure that we report each missing module import only once.

Closes #1622.